name: build-push-docker

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: GHCR Docker Buildx Build
        # You may pin to the exact commit or the version.
        # uses: bskiefer/docker_buildx@9b5f270ae6d0b02e83e32f785d5cd246d85a18eb
        uses: bskiefer/docker_buildx@v1.4
        with:
          imageName: petkit-bridge
                
